name: Issue
description: Miscellaneous issues are closed immediately. If you have no intention of returning useful information to the community, you have no right to post an issue here. Please withdraw.
body:
  - type: markdown
    attributes:
      value: |
        Anything that does not follow the issue template will be closed immediately.
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue would you like to report?
      multiple: true
      options:
        - Bug
        - Performance
        - Support
        - Feature Request
        - Documentation Feature Request
        - Documentation Bug
        - Others
    validations:
      required: true
  - type: dropdown
    id: Operating-System
    attributes:
      label: OS
      description: What OS are you seeing the issue in? If you don't see your OS listed, please provide more details in the "Description" section above.
      multiple: true
      options:
        - RaspberryPi OS Buster
        - RaspberryPi OS Stretch
        - Debian Buster
        - Debian Stretch
        - Ubuntu 21.04
        - Ubuntu 20.04
        - Ubuntu 18.04
        - Other
    validations:
      required: true
  - type: dropdown
    id: Operating-System-Architecture
    attributes:
      label: OS architecture
      description: If you don't see your architecture listed, please provide more details in the "Description" section above.
      multiple: true
      options:
        - aarch64
        - armv7
        - Other
    validations:
      required: true
  - type: dropdown
    id: Hardware
    attributes:
      label: Hardware
      description: If you don't see your device listed, please provide more details in the "Description" section above.
      multiple: true
      options:
        - RaspberryPi4
        - RaspberryPi3
        - Other
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: Please describe the current and expected behaviour, and attach all files/info needed to reproduce the issue if applicable.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell
    validations:
      required: true
